version: '3'
services:
  app:
    image: jonahirande/jonah-test:latest
    container_name: node-app
    ports:
      - 9595:9800
    environment:
      - APP_ENV="PRODUCTION"
    volumes:
        - ./db_data:/var/lib/
    command: ["node", "/app/app.js"]
  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: "passw0rd"
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3309:3306